sudo: false
dist: xenial
language: node_js
node_js:
  - '0.12'
env:
  - PHANTOMJS_BIN=node_modules/phantomjs-prebuilt/bin/phantomjs
install:
  # Disable the spinner; it looks bad on Travis.
  - npm config set spin false
before_script:
  - npm install
script:
  - npm run travis
